<img style="float: left; margin: 30px 15px 15px 15px;" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFzQj91sOlkeDFkg5HDbjtR4QJYmLXkfMNig&usqp=CAU" width="400" height="500" /> 
    
    
### <font color='navy'> Simulación matemática. 

**Nombres:**
    María del Carmen Martínez Hernández,
    Emiliano Jiménez Villaseñor
         
**Fecha:** 14 de septiembre de 2022.

**Expediente** : NT729340, IC740551
    
**Profesor:** Oscar David Jaramillo Zuluaga.
    
**Link Github**:  https://github.com/EmilianoJJ/T3Ejimenez_Mmartinez

# Tarea 3: Clase 5

## 8. Tarea 

### 8.1. Otro problema de transporte

La empresa Carbones de oriente debe ingresar a la empresa un requerimiento mínimo diario de carbón de $5000$ kg de carbón de alto volátil, $4000$ kg de medio volátil y $3000$ kg de bajo volátil para su debido proceso y trasformación. 

La entrada de estos se da en la siguiente tabla (los valores corresponden a un viaje en kg): 

-|Alto volátil|Medio volátil|Bajo volátil
:----|----|----|----
Mina sur|80|70|65
Mina norte|60|50|40
Mina central|40|30|20

El costo del trasporte de un viaje de cada mina es de 2500 dólares, 1500 dólares y 900 dólares, respectivamente. ¿Cuántos viajes de cada mina se deben recibir a diario para suplir los requerimientos mínimos y generar el menor costo de transporte? 

Para simplificar la notación use las siguientes variables: 

+ $x_1:$ Cantidad de viajes de la mina sur  
+ $x_2:$ Cantidad de viajes de la mina norte  
+ $x_3:$ Cantidad de viajes de la mina central  


El objetivo consiste consiste en plantear el problema de programación lineal que permita satisfacer los requerimientos de la empresa Carbones de oriente y resolverlo con `linprog`.

#### <font color = blue> Código de solución estudiante 1

+ $x_1:$ Cantidad de viajes de la mina sur  
+ $x_2:$ Cantidad de viajes de la mina norte  
+ $x_3:$ Cantidad de viajes de la mina central  

Minimizar coste de transporte:
$$2500 + 1500 + 900$$

$$X_1 + X_2 + X_3$$

Restricciones de consumo:
1) $80X_1 + 60X_2 + 40X_3 \geq 5000$              
2) $70X_1 + 50X_2 + 30X_3 \geq 4000$         
3) $65X_1 + 40X_2 + 20X_3 \geq 3000$

$min x_1 x_2 x_3$

In [1]:
import scipy.optimize as opt

In [2]:
import numpy as np

In [3]:
c = np.array([2500,1500,900])
b_ub = np.array([-5000,-4000,-3000])
a_ub = np.array([-80,-60,-40]),([-70,-50,-30]),([-65,-40,-20])

In [4]:
c,b_ub,a_ub

(array([2500, 1500,  900]),
 array([-5000, -4000, -3000]),
 (array([-80, -60, -40]), [-70, -50, -30], [-65, -40, -20]))

In [5]:
sol_farma = opt.linprog(c,a_ub,b_ub)

In [6]:
sol_farma

     con: array([], dtype=float64)
     fun: 119999.99941417099
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([-2.45053552e-05, -1.95627858e-05, -1.46070347e-05])
  status: 0
 success: True
       x: array([2.63641703e-09, 4.99999998e+01, 4.99999997e+01])

En conclusión pude dar con el resultado que es ningun viaje de sur, 50 viajes de norte y 50 de central. Se pudo llegar al resultado pero de por medio tuve muchos error pero se pudieron solucionar.

#### <font color = blue> Código de solución estudiante 2

Coste a minimizar

$$2500x_1 + 1500x_2 + 900x_3$$ 

Restricciones

1. La empresa debe ingresar **al menos** 5000kg diarios de <font color = blue> **carbón de alto volátil** : <font color = black> $ 80x_1 + 60x_2 + 40x_3 \geq $ <font color = blue> $ 5000 $

2. La empresa debe ingresar **al menos** 4000kg diarios de <font color = green> **carbón de medio volátil** : <font color = black> $ 70x_1 + 50x_2 + 30x_3 \geq $ <font color = green> $ 4000 $

3. La empresa debe ingresar **al menos** 3000kg diarios de <font color = orange> **carbón de medio volátil** : <font color = black> $ 65x_1 + 40x_2 + 20x_3 \geq $ <font color = orange> $ 3000 $    

El problema puede ser expresado como:
    
\begin{equation}
\begin{array}{ll}
\min_{x_1,x_2,x_3} & 2500x_1 + 1500x_2 + 900x_3 \\
\text{s. a. }      & -80x_1 - 60x_2 - 40x_3 \leq -5000  \\
                   & -70x_1 - 50x_2 - 30x_3 \leq -4000 \\
                   & -65x_1 - 40x_2 - 20x_3 \leq -3000 ,
\end{array}
\end{equation}

tomando en cuenta que 

\begin{equation}
\begin{array}{ll}
\min_{\boldsymbol{x}} & \boldsymbol{c}^\top\boldsymbol{x} \\
\text{s. a. }        
                     & \boldsymbol{A}\boldsymbol{x}\leq\boldsymbol{b},
\end{array}
\end{equation}

In [1]:
# Importar el módulo optimize de la librería scipy
import scipy.optimize as opt

In [2]:
# Importar numpy para crear las matrices
import numpy as np

In [3]:
# Crear las matrices para resolver el problema
c = np.array([2500, 1500, 900])
b_ub = np.array([-5000, -4000, -3000])
A_ub = np.array([[-80, -60, -40],
             [-70, -50, -30],
             [-65, -40, -20]])

In [4]:
c, b_ub, A_ub

(array([2500, 1500,  900]),
 array([-5000, -4000, -3000]),
 array([[-80, -60, -40],
        [-70, -50, -30],
        [-65, -40, -20]]))

In [5]:
# Resolver utilizando linprog
sol_farma = opt.linprog(c, A_ub, b_ub)

In [6]:
# Mostrar el resultado
sol_farma

     con: array([], dtype=float64)
     fun: 119999.99941417099
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([-2.45053552e-05, -1.95627858e-05, -1.46070347e-05])
  status: 0
 success: True
       x: array([2.63641703e-09, 4.99999998e+01, 4.99999997e+01])

In [7]:
# Extraer el vector solución
x = sol_farma.x
x

array([2.63641703e-09, 4.99999998e+01, 4.99999997e+01])

**Conclusión**

Se requieren de 0 viajes de la mina sur, 50 viajes de la mina norte y 50 viajes de la mina central para cumplir con los requerimientos mínimos de carbon solicitados diariamente y a su vez generar el menor costo posible, que es de 120000 dólares.

### 8.2. 
Una empresa de muebles rústicos fabrica entre muchos otros productos cinco tipos de sillas A, B, C, D Y E, las cuales se venden a precio de $1100$, $1300$, $1200$, $980$ y $1010$ pesos cada una y respectivamente. 

Las sillas pasan por cinco procesos: corte, ensamblado, lijado, pintado y sellado, para lo cual se dispone máximo de $17$, $11$, $15$, $12$ y $14$ horas respectivamente a la semana para dedicar a estas operaciones a estos productos.

Los requerimientos, en horas, para cada una de las sillas está dado en la siguiente tabla:

-|Corte|Ensamblado|Lijado|Pintado|Sellado
:----|----|----|----|----|----
Silla A|3|1|3|1|1
Silla B|2|3|2|2|3
Silla C|5|2|2|3|1
Silla D|2|4|1|1|2
Silla E|1|0|2|2|3

¿Cuántas sillas de cada tipo se deben fabricar para suplir los requerimientos de disponibiladas semanal y generar la mayor utilidad en ventas? 

Para simplificar la notación use las siguientes variables: 

+ $x_A:$ Cantidad de sillas tipo A 
+ $x_B:$ Cantidad de sillas tipo B 
+ $x_C:$ Cantidad de sillas tipo C 
+ $x_D:$ Cantidad de sillas tipo D  
+ $x_E:$ Cantidad de sillas tipo E


El objetivo consiste consiste en plantear el problema de programación lineal que permita satisfacer los requerimientos de la empresa empresa de muebles y resolverlo con `linprog`.

#### <font color = blue> Código de solución estudiante 1

+ $x_A:$ Cantidad de sillas tipo A 
+ $x_B:$ Cantidad de sillas tipo B 
+ $x_C:$ Cantidad de sillas tipo C 
+ $x_D:$ Cantidad de sillas tipo D  
+ $x_E:$ Cantidad de sillas tipo E

Maximizar:
$$1100 + 1300 + 1200 + 980 + 1010$$
$$ X_a + X_b  +  X_c + X_d + X_e$$

Restricciones
1) $3X_a + 2X_b + 5X_c + 2X_d + X_e \leq 17$

2) $X_a + 3X_b + 2X_c + 4X_d \leq 11$

3) $3X_a + 2X_b + 2X_c + X_d + 2X_e \leq 15$

4) $X_a + 2X_b + 3X_c + X_d + 2_Xe \leq 12$

5) $X_a + 3X_b + X_c + 2X_d + 3X_e \leq 14$

$max X_a X_b X_c X_d X_e$

In [7]:
c = np.array([-1100,-1300,-1200,-980,-1010])
b_ub = np.array([17,11,15,12,14])
a_ub = np.array([3,2,5,2,1]),([1,3,2,4,0]),([3,2,2,1,2]),([1,2,3,1,2]),([1,3,1,2,3])

In [8]:
c,b_ub,a_ub

(array([-1100, -1300, -1200,  -980, -1010]),
 array([17, 11, 15, 12, 14]),
 (array([3, 2, 5, 2, 1]),
  [1, 3, 2, 4, 0],
  [3, 2, 2, 1, 2],
  [1, 2, 3, 1, 2],
  [1, 3, 1, 2, 3]))

In [9]:
sol_farma = opt.linprog(c,a_ub,b_ub)

In [10]:
sol_farma

     con: array([], dtype=float64)
     fun: -7699.999999956917
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([7.55839835e-11, 4.15312229e-12, 9.37241396e-11, 1.69810832e-10,
       7.65005836e-11])
  status: 0
 success: True
       x: array([2., 1., 1., 1., 2.])

En conclusión se ocupan hacer: 2 sillas A, 1 silla B, 1 silla C, 1 silla D y 2 sillas E.

#### <font color = blue> Código de solución estudiante 2

Coste a maximizar

$$1100x_A + 1300x_B + 1200x_C + 980x_D + 1010x_E$$ 

Restricciones

$ 3x_A + 2x_B + 5x_C + 2x_D + x_E \leq 17 $

$ x_A + 3x_B + 2x_C + 4x_D \leq 11 $

$ 3x_A + 2x_B + 2x_C + x_D + 2x_E \leq 15 $

$ x_A + 2x_B + 3x_C + x_D + 2x_E \leq 12 $

$ x_A + 3x_B + x_C + 2x_D + 3x_E \leq 14 $

El problema puede ser expresado como:
    
\begin{equation}
\begin{array}{ll}
\min_{x_A,x_B...} & -1100x_A - 1300x_B - 1200x_C - 980x_D - 1010x_E \\
\text{s. a. }  & 3x_A + 2x_B + 5x_C + 2x_D + x_E \leq 17 \\
               & x_A + 3x_B + 2x_C + 4x_D \leq 11 \\
               & 3x_A + 2x_B + 2x_C + x_D + 2x_E \leq 15 \\
               & x_A + 2x_B + 3x_C + x_D + 2x_E \leq 12 \\
               & x_A + 3x_B + x_C + 2x_D + 3x_E \leq 14 ,
\end{array}
\end{equation}

tomando en cuenta que

\begin{equation}
\begin{array}{ll}
\min_{\boldsymbol{x}} & \boldsymbol{c}^\top\boldsymbol{x} \\
\text{s. a. }        
                     & \boldsymbol{A}\boldsymbol{x}\leq\boldsymbol{b},
\end{array}
\end{equation}

In [8]:
# Importar el módulo optimize de la librería scipy
import scipy.optimize as opt

In [9]:
# Importar numpy para crear las matrices
import numpy as np

In [10]:
# Crear las matrices para resolver el problema
c = np.array([-1100, -1300, -1200, -980, -1010])
b_ub = np.array([17, 11, 15, 12, 14])
A_ub = np.array([[3,2,5, 2, 1],
             [1, 3, 2, 4, 0],
             [3, 2, 2, 1, 2],    
             [1, 2, 3, 1, 2],
             [1, 3, 1, 2, 3]])

In [11]:
c, b_ub, A_ub

(array([-1100, -1300, -1200,  -980, -1010]),
 array([17, 11, 15, 12, 14]),
 array([[3, 2, 5, 2, 1],
        [1, 3, 2, 4, 0],
        [3, 2, 2, 1, 2],
        [1, 2, 3, 1, 2],
        [1, 3, 1, 2, 3]]))

In [12]:
# Resolver utilizando linprog
sol_farma = opt.linprog(c, A_ub, b_ub)

In [13]:
# Mostrar el resultado
sol_farma

     con: array([], dtype=float64)
     fun: -7699.999999956917
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([7.55839835e-11, 4.15312229e-12, 9.37241396e-11, 1.69810832e-10,
       7.65005836e-11])
  status: 0
 success: True
       x: array([2., 1., 1., 1., 2.])

In [14]:
# Extraer el vector solución
x = sol_farma.x
x

array([2., 1., 1., 1., 2.])

**Conclusión** 

Se requiere fabricar:
+ 2 sillas tipo A 
+ 1 silla tipo B 
+ 1 silla tipo C
+ 1 silla tipo D
+ 2 sillas tipo E,

para suplir los requerimientos semanales y a su vez generar la mayor utilidad en ventas.